site :opscode

# automatically includes all cookbooks in the cookbooks folder
# AND their dependencies.
Dir[File.expand_path('*/')].each do |path|  
  File.directory?(path) || next
  cookbook(File.basename(path), path: path)
  Dir.chdir(path) do
    result = %x{unset GEM_HOME BUNDLE_BIN_PATH BUNDLE_GEMFILE RUBYOPT RUBYLIB GEM_PATH; berks -d 2>&1}
  end
end 

